if(${target}_UIC_UNITS)
    foreach(unit ${${target}_UIC_UNITS})
        append(${target}_UIC ${unit}.ui)
        append(${target}_MOC ${unit}.h)
        append(${target}_SOURCES
            ${unit}.cpp
            ${unit}.h
        )
    endforeach()
endif()
if(${target}_UIC)
    if(QT5)
        qt5_wrap_ui(${target}_UIC_SOURCES ${${target}_UIC})
    else()
        qt4_wrap_ui(${target}_UIC_SOURCES ${${target}_UIC})
    endif()
    append(${target}_SOURCES ${${target}_UIC} ${${target}_UIC_SOURCES})
endif()
if(${target}_MOC_UNITS)
    foreach(unit ${${target}_MOC_UNITS})
        append(${target}_MOC ${unit}.h)
        append(${target}_SOURCES
            ${unit}.cpp
            ${unit}.h
        )
    endforeach()
endif()
if(${target}_MOC)
    if(QT5)
        qt5_wrap_cpp(${target}_MOC_SOURCES ${${target}_MOC})
    else()
        qt4_wrap_cpp(${target}_MOC_SOURCES ${${target}_MOC})
    endif()
    append(${target}_SOURCES ${${target}_MOC_SOURCES})
endif()
if(${target}_JS)
    set(js_qrc ${CMAKE_CURRENT_BINARY_DIR}/${target}-js.qrc)
    dir2code(${js_qrc} ${${target}_JS})
    target_add_qrc(${target} ${js_qrc} ${target}-js ${${target}_JS})
    append(${target}_GENERATED ${js_qrc})
    append(${target}_FILES ${${target}_JS})
    register_target_files(${target} JS js)
endif()
if(${target}_QML)
    set(qmldir ${CMAKE_CURRENT_BINARY_DIR}/${target}-qmldir)
    set(qml_qrc ${CMAKE_CURRENT_BINARY_DIR}/${target}-qml.qrc)
    dir2code(${qmldir} ${${target}_QML})
    dir2code(${qml_qrc} ${${target}_QML} ${qmldir})
    append(${target}_GENERATED ${qml_qrc} ${qmldir})
    target_add_qrc(${target} ${qml_qrc} ${target}-qml ${${target}_QML})
    append(${target}_FILES ${${target}_QML} ${qmldir})
    register_target_files(${target} QML qml)
endif()
if(${target}_GFX)
    set(gfx_qrc ${CMAKE_CURRENT_BINARY_DIR}/${target}-gfx.qrc)
    dir2code(${gfx_qrc} ${${target}_GFX})
    target_add_qrc(${target} ${gfx_qrc} ${target}-gfx ${${target}_GFX})
    append(${target}_GENERATED ${gfx_qrc})
    append(${target}_FILES ${${target}_GFX})
    register_target_files(${target} GFX gfx)
endif()
if(${target}_QRC)
    if(QT5)
        qt5_add_resources(${target}_QRC_SOURCES ${${target}_QRC})
    else()
        qt4_add_resources(${target}_QRC_SOURCES ${${target}_QRC})
    endif()
    append(${target}_SOURCES ${${target}_QRC} ${${target}_QRC_SOURCES})
endif()
