if(${T}_UIC_UNITS)
    foreach(unit ${${T}_UIC_UNITS})
        target_append(${T} UIC ${unit}.ui)
        target_append(${T} MOC ${unit}.h)
        target_append(${T} SOURCES
            ${unit}.cpp
            ${unit}.h
        )
    endforeach()
endif()
if(${T}_UIC)
    if(QT5)
        qt5_wrap_ui(${T}_UIC_SOURCES ${${T}_UIC})
    else()
        qt4_wrap_ui(${T}_UIC_SOURCES ${${T}_UIC})
    endif()
    target_append(${T} SOURCES ${${T}_UIC} ${${T}_UIC_SOURCES})
endif()
if(${T}_MOC_UNITS)
    foreach(unit ${${T}_MOC_UNITS})
        target_append(${T} MOC ${unit}.h)
        target_append(${T} SOURCES
            ${unit}.cpp
            ${unit}.h
        )
    endforeach()
endif()
if(${T}_MOC)
    if(QT5)
        qt5_wrap_cpp(${T}_MOC_SOURCES ${${T}_MOC})
    else()
        qt4_wrap_cpp(${T}_MOC_SOURCES ${${T}_MOC})
    endif()
    target_append(${T} SOURCES ${${T}_MOC_SOURCES})
    message("target_append(${T} SOURCES ${${T}_MOC_SOURCES})")
endif()
if(${T}_JS)
    set(js_qrc ${HERE_BIN}/${T}-js.qrc)
    dir2code(${js_qrc} ${${T}_JS})
    target_add_qrc(${T} ${js_qrc} ${T}-js ${${T}_JS})
    target_append(${T} GENERATED ${js_qrc})
    target_append(${T} FILES ${${T}_JS})
    register_target_files(${T} JS js)
endif()
if(${T}_QML)
    set(qmldir ${HERE_BIN}/${T}-qmldir)
    set(qml_qrc ${HERE_BIN}/${T}-qml.qrc)
    dir2code(${qmldir} ${${T}_QML})
    dir2code(${qml_qrc} ${${T}_QML} ${qmldir})
    target_append(${T} GENERATED ${qml_qrc} ${qmldir})
    target_add_qrc(${T} ${qml_qrc} ${T}-qml ${${T}_QML})
    target_append(${T} FILES ${${T}_QML} ${qmldir})
    register_target_files(${T} QML qml)
endif()
if(${T}_GFX)
    set(gfx_qrc ${HERE_BIN}/${T}-gfx.qrc)
    dir2code(${gfx_qrc} ${${T}_GFX})
    target_add_qrc(${T} ${gfx_qrc} ${T}-gfx ${${T}_GFX})
    target_append(${T} GENERATED ${gfx_qrc})
    target_append(${T} FILES ${${T}_GFX})
    register_target_files(${T} GFX gfx)
endif()
if(${T}_QRC)
    if(QT5)
        qt5_add_resources(${T}_QRC_SOURCES ${${T}_QRC})
    else()
        qt4_add_resources(${T}_QRC_SOURCES ${${T}_QRC})
    endif()
    target_append(${T} SOURCES ${${T}_QRC} ${${T}_QRC_SOURCES})
endif()
