if(${T}_STRICT)
    foreach(src ${${T}_SOURCES})
        get_source_language(${src} src_lang)
        get_global(REMAKE_STRICT_C_FLAGS)
        get_global(REMAKE_STRICT_CXX_FLAGS)
        if(src_lang STREQUAL "C" AND DEFINED REMAKE_STRICT_C_FLAGS)
            set_property(SOURCE ${src} APPEND PROPERTY COMPILE_FLAGS ${REMAKE_STRICT_C_FLAGS})
        elseif(src_lang STREQUAL "CXX" AND DEFINED REMAKE_STRICT_CXX_FLAGS)
            set_property(SOURCE ${src} APPEND PROPERTY COMPILE_FLAGS ${REMAKE_STRICT_CXX_FLAGS})
        endif()
    endforeach()
endif()
